-- 코드를 입력하세요
SELECT A.CART_ID
FROM ((SELECT 
    CP.ID AS ID, 
    CP.CART_ID AS CART_ID
FROM
    CART_PRODUCTS CP
WHERE CP.NAME LIKE 'Milk') A 
JOIN (SELECT 
    CP.ID AS ID, 
    CP.CART_ID AS CART_ID
FROM
    CART_PRODUCTS CP
WHERE CP.NAME LIKE 'Yogurt'
) B ON A.CART_ID = B.CART_ID)
ORDER BY A.CART_ID;