-- 코드를 작성해주세요
WITH F AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
),
S AS (
    SELECT ED.ID
    FROM ECOLI_DATA ED
    JOIN F FF ON ED.PARENT_ID = FF.ID
)
SELECT ED.ID AS ID
FROM ECOLI_DATA ED
JOIN S SS ON ED.PARENT_ID = SS.ID
ORDER BY ED.ID;