-- 코드를 입력하세요
WITH OFS AS (
    SELECT 
        DATE_FORMAT(OS.SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
        OS.PRODUCT_ID AS PRODUCT_ID,
        OS.USER_ID AS USER_ID,
        OS.SALES_AMOUNT AS SALES_AMOUNT
    FROM ONLINE_SALE OS
    WHERE DATE_FORMAT(OS.SALES_DATE,'%Y-%m') = '2022-03'
    
    UNION ALL
    
    SELECT 
        DATE_FORMAT(OFF.SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
        OFF.PRODUCT_ID AS PRODUCT_ID,
        NULL AS USER_ID,
        OFF.SALES_AMOUNT AS SALES_AMOUNT
    FROM OFFLINE_SALE OFF
    WHERE DATE_FORMAT(OFF.SALES_DATE,'%Y-%m') = '2022-03'
)
SELECT * FROM OFS
ORDER BY SALES_DATE,PRODUCT_ID,USER_ID;
