-- 코드를 입력하세요



SELECT 
    RI.REST_ID AS REST_ID,
    RI.REST_NAME AS REST_NAME,
    RI.FOOD_TYPE AS FOOD_TYPE,
    RI.FAVORITES AS FAVORITES,
    RI.ADDRESS AS ADDRESS,
    A.SCORE
FROM REST_INFO RI JOIN
(   
    SELECT
    RR.REST_ID AS REST_ID, ROUND(AVG(RR.REVIEW_SCORE),2) AS SCORE
    FROM REST_REVIEW RR
    GROUP BY REST_ID
) A ON RI.REST_ID = A.REST_ID
WHERE ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC;