-- 코드를 입력하세요
SELECT FP.PRODUCT_ID AS PRODUCT_ID, FP.PRODUCT_NAME AS PRODUCT_NAME,
(FP.PRICE * A.TT) AS TOTAL_PRICE
FROM FOOD_PRODUCT FP JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TT
    FROM FOOD_ORDER 
    WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
    GROUP BY PRODUCT_ID
) A ON FP.PRODUCT_ID = A.PRODUCT_ID
ORDER BY TOTAL_PRICE DESC, PRODUCT_ID;




# SELECT *
# FROM FOOD_ORDER;