-- 코드를 입력하세요
WITH DL AS (
    SELECT
        HISTORY_ID,
        CAR_ID,
        DATEDIFF(DATE_FORMAT(END_DATE,'%Y-%m-%d'),DATE_FORMAT(START_DATE,'%Y-%m-%d')) + 1 AS DIF
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
),
CCC AS (
    SELECT
        D.HISTORY_ID AS HISTORY_ID,
        D.CAR_ID AS CAR_ID,
        D.DIF AS DIF,
        AC.DAILY_FEE AS DF
    FROM DL D 
    JOIN CAR_RENTAL_COMPANY_CAR AC
    ON D.CAR_ID = AC.CAR_ID
    WHERE AC.CAR_TYPE LIKE '트럭'
) SELECT 
    C.HISTORY_ID AS HISTORY_ID,
    CONVERT(((C.DF * C.DIF) / 100 * (100 -
    (CASE
        WHEN C.DIF >= 90 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE LIKE '트럭' AND DURATION_TYPE LIKE '90일 이상')
        WHEN C.DIF >= 30 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE LIKE '트럭' AND DURATION_TYPE LIKE '30일 이상')
        WHEN C.DIF >= 7 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE LIKE '트럭' AND DURATION_TYPE LIKE '7일 이상')
        ELSE 0
    END))),UNSIGNED) FEE
FROM CCC C
ORDER BY FEE DESC, HISTORY_ID DESC;