-- 코드를 입력하세요

SELECT 
    AP.APNT_NO AS APNT_NO, 
    P.PT_NAME AS PT_NAME, 
    AP.PT_NO AS PT_NO, 
    AP.MCDP_CD AS MCDP_CD,
    D.DR_NAME AS DR_NAME,
    AP.APNT_YMD AS APNT_YMD
FROM APPOINTMENT AP 
    JOIN PATIENT P ON P.PT_NO = AP.PT_NO
    JOIN DOCTOR D ON D.DR_ID = AP.MDDR_ID
WHERE DATE_FORMAT(AP.APNT_YMD,'%Y-%m-%d') = '2022-04-13'
AND AP.APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD;