-- 코드를 입력하세요
WITH recursive CTE AS
(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT 
        HOUR + 1 FROM CTE
    WHERE HOUR < 23
)
SELECT 
    C.HOUR AS HOUR,
    CASE
        WHEN A.COUNT IS NULL THEN 0
        ELSE A.COUNT
    END 'COUNT'
FROM CTE C LEFT JOIN (
SELECT
    DATE_FORMAT(AO.DATETIME,"%H") AS HOUR,
    COUNT(ANIMAL_ID) AS 'COUNT'
FROM ANIMAL_OUTS AO
GROUP BY HOUR
ORDER BY HOUR) A ON C.HOUR = A.HOUR;