-- 코드를 작성해주세요
WITH FS AS (
    SELECT SUM(S.CODE) AS 'CODE'
    FROM SKILLCODES S
    WHERE CATEGORY LIKE 'Front End'
)
SELECT 
    D.ID,
    D.EMAIL,
    D.FIRST_NAME,
    D.LAST_NAME
FROM DEVELOPERS D
WHERE D.SKILL_CODE & (SELECT * FROM FS) >= 1
ORDER BY D.ID;