-- 코드를 입력하세요
WITH TRR AS (
    SELECT 
        MEMBER_ID, 
        COUNT(MEMBER_ID) AS TOTAL
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY TOTAL DESC
),
MAX_COUNT AS (
    SELECT MAX(TOTAL) AS MAXY
    FROM TRR
)
SELECT 
    MP.MEMBER_NAME AS MEMBER_NAME,
    RR.REVIEW_TEXT AS REVIEW_TEXT,
    DATE_FORMAT(RR.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW RR JOIN MEMBER_PROFILE MP ON RR.MEMBER_ID = MP.MEMBER_ID
JOIN TRR TT ON RR.MEMBER_ID = TT.MEMBER_ID
JOIN MAX_COUNT MM 
WHERE TT.TOTAL = MM.MAXY
ORDER BY REVIEW_DATE, REVIEW_TEXT;