-- 코드를 입력하세요
# SELECT CC.CAR_ID AS CAR_ID FROM CAR_RENTAL_COMPANY_CAR CC
# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
# ON CC.CAR_ID = CH.CAR_ID
# WHERE CC.CAR_TYPE LIKE '세단'
# AND MONTH(CH.START_DATE) = 10
# ORDER BY CC.CAR_ID DESC;

SELECT DISTINCT(CC.CAR_ID) AS CAR_ID FROM CAR_RENTAL_COMPANY_CAR CC
JOIN (
        SELECT CH.CAR_ID AS CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
        WHERE MONTH(CH.START_DATE) = 10
     ) CHH
ON CC.CAR_ID = CHH.CAR_ID
WHERE CC.CAR_TYPE LIKE '세단'
ORDER BY CC.CAR_ID DESC;