-- 코드를 작성해주세요
WITH FRONTEND AS (
    SELECT SUM(F.CODE)
    FROM SKILLCODES F
    WHERE F.CATEGORY LIKE 'Front End'
),
CC AS (
    SELECT F.CODE
    FROM SKILLCODES F
    WHERE F.NAME LIKE 'C#'
),
PP AS (
    SELECT F.CODE
    FROM SKILLCODES F
    WHERE F.NAME LIKE 'Python'
),
FFF AS (
SELECT
    CASE
        WHEN D.SKILL_CODE & (SELECT * FROM FRONTEND) >= 1 AND D.SKILL_CODE & (SELECT * FROM PP) >= 1 THEN 'A'
        WHEN D.SKILL_CODE & (SELECT * FROM CC) >= 1 THEN 'B'
        WHEN D.SKILL_CODE & (SELECT * FROM FRONTEND) >= 1 THEN 'C'
        ELSE NULL
    END GRADE,     
    D.ID AS ID,
    D.EMAIL AS EMAIL
FROM DEVELOPERS D
)
SELECT * FROM FFF
WHERE FFF.GRADE IS NOT NULL
ORDER BY GRADE,ID;